CREATE TABLE IF NOT EXISTS hits (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app         VARCHAR(64) not null,
    uri         VARCHAR(256) not null,
    ip          VARCHAR(64) not null,
    time_stamp  TIMESTAMP WITHOUT TIME ZONE not null
);